### ISSUE TITLE
Fix `network::tcp_listener::listen()` to fail when binding to an invalid endpoint

### ISSUE THREAD

**Issue by metalicjames** [mit-dci/opencbdc-tx#11]
Also add a unit test for this case, and re-enable the disabled archiver unit test marked with a TODO related to this failure.

**Comment by EnrikoChavez** [comment]
Hi team,
I've been looking at this issue as my good first issue. As I've been looking around it looks to me that listen() does not fail with an invalid input. Instead it seems to be an issue in which the archiver test expected aliasing to happen, but instead a copy of a variable happened. So it never actually tested an invalid input. I added a new variable that takes in the modified input that has an invalid endpoint, and tested for it to fail, which it did. Let me know if this seems right, and I'd love to talk about this further if there is anything to discuss. I'd be ready to add a pull request for this if it seems right. Thanks!

as explained in the second latest commit message in https://github.com/EnrikoChavez/opencbdc-tx/tree/trunk:

    Fixed failure that made listen() appear to fail when binding to an invalid endpoint
    
    Created a new m_archiver_invalid_endpoint variable to be able to add the edited variable
    that has the invalid endpoint on it. Have to create new m_archiver_invalid_endpoint
    variable because editing the vector that includes the invalid endpoint does not work since
    a copy of the vector gets passed down according to controller initializer, not a reference of it.
    
    The archiver test "archiver_server_init_failure" failed beforehand, which made it seem
    as if connecting to an invalid endpoint still allowed the server to be initialized. Turns
    out that the test was the problem. The test used to edit m_config_opts, however m_config_opts
    did not get changed inside m_archiver, since m_config_opts was copied into m_archiver during
    initialization, not referenced to it. Now the test has a new m_archiver that has the m_config_opts
    variable changes ever since initialization, allowing test to fail to bind to it.

**Comment by HalosGhost** [comment]
Welcome! I can pull your code and take a look at it, but it's much easier for me (and everyone else) to review your contribution if you make a pull request as soon as you think it is ready for review. It also gives us tools to review the specific patch, and make recommendations inline.

If you think it's ready for us to take a look, please open a pull request (and, in the commit text, include `closes #11` to link the PR to this issue)!
