### ISSUE TITLE
[atomizer::state_machine] fix assertion failure in create_snapshot() and clarify meaning of last committed log index

### ISSUE THREAD

**Issue by AlexRamRam** [mit-dci/opencbdc-tx#125]
### Affected Branch

trunk

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [X] The issue is reproducible in docker

### Synopsis
In `cbdc::atomizer::state_machine::create_snapshot(snapshot& s ...)` we 
[`assert(s.get_last_log_idx() == last_commit_index())`](https://github.com/mit-dci/opencbdc-tx/blob/7e3dd76ec4e4d13ab78f8c0f372fad670240affa/src/uhs/atomizer/atomizer/state_machine.cpp#L206)
where `last_commit_index()` returns the last log index processed by [`::commit()`](https://github.com/mit-dci/opencbdc-tx/blob/7e3dd76ec4e4d13ab78f8c0f372fad670240affa/src/uhs/atomizer/atomizer/state_machine.cpp#L42).

When snapshot is enabled, the assertion fails because log index last processed by [`::commit()`](https://github.com/mit-dci/opencbdc-tx/blob/7e3dd76ec4e4d13ab78f8c0f372fad670240affa/src/uhs/atomizer/atomizer/state_machine.cpp#L42) is often smaller than the requested snapshot log index.
This is because NuRaft creates log entries for cluster configuration changes which invoke [`state_machine::commit_config(...)`](https://github.com/eBay/NuRaft/blob/9d7c4cb04d0fe0e18e6b2ae4fbef503bfa7da8f0/include/libnuraft/state_machine.hxx#L77-L84) instead of the application log commit [state_machine::commit(...)](https://github.com/eBay/NuRaft/blob/9d7c4cb04d0fe0e18e6b2ae4fbef503bfa7da8f0/include/libnuraft/state_machine.hxx#L51-L67).  See NuRaft's [commit thread](https://github.com/eBay/NuRaft/blob/9d7c4cb04d0fe0e18e6b2ae4fbef503bfa7da8f0/src/handle_commit.cxx#L233-L238) for  details.
This optional hook [`state_machine::commit_config(...)`](https://github.com/eBay/NuRaft/blob/9d7c4cb04d0fe0e18e6b2ae4fbef503bfa7da8f0/include/libnuraft/state_machine.hxx#L77-L84) is currently unimplemented for `atomizer::state_machine`, therefore the state machine's self-maintained last commit index is not in sync with the system's last log index.

### Two potential solutions:
1) Pretend the in-memory state machine "comits" cluster configuration change logs. Keep the assertion in place, and sync the last commited log index (`::m_last_commited_idx`) with the last snapshot log index by implementing the optional and otherwise empty callback `::commit_config()` like so:
```
    void state_machine::commit_config(const nuraft::ulong log_idx,
                                      nuraft::ptr<nuraft::cluster_config>&) {
        m_last_committed_idx = log_idx;
    }
```
Keeping `m_last_committed_idx` in sync in this way with the system log index provides additional assurance that the state machine is up-to-date. However, this assurance is likely already provided by the framework and may not be necessary (I'm not sure about this!). In any case, this provides clarity and comfort.
This may become fragile as NuRaft implementation changes over time (i.e. different cluster management message types are added invoking different hooks).

2) Manage only what we care about. Maintain the last commit index as we do now with the understanding that, currently, the state_machine only cares about application log entries via `::commit()`.  We relax the assertion accordingly (`assert(s.get_last_log_idx() >= last_commit_index());`), and explicitly save/re-populate this value in `create_snapshot()`/`apply_snapshot()` by adding new member `m_last_committed_idx`
to member struct [`cbdc::atomzier::state_machine::snapshot`](https://github.com/mit-dci/opencbdc-tx/blob/7e3dd76ec4e4d13ab78f8c0f372fad670240affa/src/uhs/atomizer/atomizer/state_machine.hpp#L115-L124)

### In order to reproduce the issue, follow these steps:

1. Enable snapshot feature: in `replicated_atomizer.cfg` add line `snapshot_distance=2`
2. `tests/integration/run_integration_tests --gtest_filter=replicated_atomizer_integration_tests.*`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HalosGhost** [comment]
Can you expand on the trade-offs of the two solutions? The first solution offers some additional clarity, but might become fragile due to relying on internal hooks of nuraft. The second solution seems lighter-weight and puts us in the driver's seat on what we care about. Is the only trade-off of the second solution that there will be a few more lines of code to manage the manual indexing and a relaxed assertion?

**Comment by AlexRamRam** [comment]
Yes - I've added to the solution #1 section. @metalicjames  will let us know what other considerations I may have missed.
