### ISSUE TITLE
config.sh breaks for Apple Silicon Macs due to new homebrew install prefix

### ISSUE THREAD

**Issue by AlexRamRam** [mit-dci/opencbdc-tx#139]
### Affected Branch

On Apple Silicon Macs, [Homebrew's install prefix has changes](https://github.com/Homebrew/brew/issues/9177) from `/usr/local` to `/opt/homebrew`. As a result, `scripts/config.sh` fails where it references `/usr/local/bin`

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [ ] The issue is reproducible in docker

### Description

Run `./scripts/config.sh` on an Apple Silicon Mac.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonwiggins** [comment]
Hmm, I tried to fix this in #116  by using `$(brew --prefix)`
https://github.com/mit-dci/opencbdc-tx/blob/aa10a7a9de42c009a834c32b90c1a01799a80c67/scripts/configure.sh#L32
What is the error you get? Maybe if the `/usr/local/bin` directory doesn't exist I should have added a check that will make it if needed.

**Comment by AlexRamRam** [comment]
I see. Yes, `/usr/local` can be empty.
I'm motivated to propose changes to keep things within the brew ecosystem (minimizing affecting `/usr/local`), as well as addressing the potentially missing dirs in `/usr/local`. Also, `gmake` is covered by `brew install make`; it looks like that can be removed:
```
elif [[ "$OSTYPE" == "darwin"* ]]; then
  CPUS=$(sysctl -n hw.ncpu)
  # ensure development environment is set correctly for clang
  $SUDO xcode-select -switch /Library/Developer/CommandLineTools
  brew install leveldb llvm@11 googletest lcov make wget cmake

  for CLANG_ITEM in "clang-tidy" "clang-format"
  do
    if [ ! -L "$(brew --prefix)/bin/$CLANG_ITEM" ]; then
      ln -s $(brew --prefix llvm@11)/bin/$CLANG_ITEM $(brew --prefix)/bin/$CLANG_ITEM
    fi
  done
fi
```
Additionally, we add `mkdir -p /usr/local/lib /usr/local/include` in the penultimate Nuraft portion, and add `mkdir -p /usr/local/bin` for the final `run-clang-tidy` block (annoyingly `run-clang-tidy` is part of llvm@13, but not 11).

@jonwiggins : your thoughts would be appreciated.

**Comment by jonwiggins** [comment]
If you test it and that works then it should be fine. I don't recall exactly what the issue was, but I'm sure I wouldn't have linked those clang things into `/urs/local` unless something was looking for them there.

> Also, gmake is covered by brew install make

Hmm, I wonder why I didn't have it then. I wouldn't have added that line if I got it from `brew install make`.

**Comment by HalosGhost** [comment]
@AlexRamRam any word on this?

**Comment by AlexRamRam** [comment]
This is no longer an issue - tested on a new MacOS system.
