### ISSUE TITLE
Non-existent element access and infinite loop in sentinel_2pc::controller

### ISSUE THREAD

**Issue by mszulcz-mitre** [mit-dci/opencbdc-tx#141]
### Affected Branch

trunk

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [X] The issue is reproducible in docker

### Description

# Problems
I’ve observed 2 issues with `sentinel_2pc::controller::gather_attestations`:  a non-existent element access and an infinite loop.

### 1. Non-existent element access
When `m_sentinel_endpoints.size() = 1` and `m_attestation_threshold > 1`, a non-existent element in the vector `m_sentinel_clients` is accessed.   The access results in undefined behavior, but in my tests, a seg. fault is usually thrown.  The access occurs on Line 166 in src/uhs/twophase/sentinel_2pc/controller.cpp (lines 165 - 176 shown below):
```c++
                success
                    = m_sentinel_clients[sentinel_id]->validate_transaction(
                        tx,
                        [=](validate_result v_res) {
                            auto r = requested;
                            r.insert(sentinel_id);
                            validate_result_handler(v_res,
                                                    tx,
                                                    result_callback,
                                                    ctx,
                                                    r);
                        });
```
To reproduce the error, add this test to controller_test.cpp:
```c++
TEST_F(sentinel_2pc_test, nonexistent_element_access_in_gather_attestations) {
    m_opts.m_attestation_threshold = 2;
    auto ctl = std::make_unique<cbdc::sentinel_2pc::controller>(0,
                                                                m_opts,
                                                                m_logger);
    ASSERT_TRUE(ctl->init());

    // The next line causes a non-existent element to be accessed when 
    // execute_transaction calls gather_attestations.
    auto res = ctl->execute_transaction(m_valid_tx, [](auto /* param */) {});
    ASSERT_TRUE(res);
}
```

## 2.  Infinite loop   

When the number of required sentinel attestations is larger than the number of sentinels, an infinite loop can be triggered in `sentinel_2pc::controller:;gather_attestations`. The infinite loop occurs because the condition on Line 158 in src/uhs/twophase/sentinel_2pc/controller.cpp can never be satisfied:
```
 if(ctx.m_attestations.size() < m_opts.m_attestation_threshold) {
```
Sometimes the loop will eventually throw a seg. fault, but I don’t know why yet.   

To reproduce the problem, add this test to controller_test.cpp:
```c++
TEST_F(sentinel_2pc_test, execute_transaction_triggers_infinite_loop) {
    // Require 3 sentinel attestations.  This requirement is impossible to
    // achieve since this test only launches 2 sentinels.
    m_opts.m_attestation_threshold = 3;

    // Define 2nd sentinel controller (the 1st is defined in the fixture).
    unsigned short sentinel_port = 32003;
    auto sentinel_ep
        = std::make_pair(cbdc::network::localhost, sentinel_port);
    m_opts.m_sentinel_endpoints.push_back(sentinel_ep);
    constexpr auto sentinel_private_key
        = "000000000000000100000000000000000000000000000000000000000000000"
            "1";
    constexpr auto sentinel_public_key
        = "eaa649f21f51bdbae7be4ae34ce6e5217a58fdce7f47f9aa7f3b58fa2120e2b"
            "4";
    m_opts.m_sentinel_private_keys[1]
        = cbdc::hash_from_hex(sentinel_private_key);
    m_opts.m_sentinel_public_keys.insert(
        cbdc::hash_from_hex(sentinel_public_key));

    // Initialize the 1st sentinel controller.
    auto ctl = std::make_unique<cbdc::sentinel_2pc::controller>(0,
                                                                m_opts,
                                                                m_logger);
    ASSERT_TRUE(ctl->init());


    // Initialize the 2nd sentinel controller.
    auto ctl2 = std::make_unique<cbdc::sentinel_2pc::controller>(1,
                                                            m_opts,
                                                            m_logger);
    ASSERT_TRUE(ctl2->init());

    // This line will trigger an infinite loop when execute transaction calls
    // gather_attestations.
    auto res = ctl->execute_transaction(m_valid_tx, [](auto /* param */) {});
    ASSERT_TRUE(res);
}

```

# Solutions
To prevent these errors, we could add two bits of code to `sentinel_2pc::controller::init`.

1.  We could prevent accidental casting that occurs when defining the distribution `m_dist` (Line 57 in src/uhs/twophase/sentinel_2pc/controller.cpp):
```c++
m_dist = decltype(m_dist)(0, m_sentinel_clients.size() - 1);
```
When `m_sentinel_clients.size() = 0`, the second argument to `m_dist` above is -1, which is then cast to an unsigned integer.  In my tests, it  becomes 18446744073709551615.  To prevent this, we could replace the current definition of `m_dist` with:
```c++
constexpr size_t dist_lower_bound = 0;
const size_t dist_upper_bound 
	= m_sentinel_clients.empty() ? 0 : m_sentinel_clients.size() - 1;
m_dist = decltype(m_dist)(dist_lower_bound, dist_upper_bound);
```
This ensures that the `sentinel_id` defined on Line 161 in `sentinel_2pc::controller::gather_attestations` remains a reasonable number:
```c++
auto sentinel_id = m_dist(m_rand);
```

2.  We could add the following to `sentinel_2pc::controller::init` to check that the required number of attestations never exceeds the number of sentinels:
```c++
        if(m_opts.m_attestation_threshold
            > m_opts.m_sentinel_endpoints.size()) {
            m_logger->error("The number of required attestations is larger \n \
                than the number of sentinels that can provide them.");
            return false;
        } 
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HalosGhost** [comment]
Both of these are good catches. I'm resoundingly in-favor of putting this in the initialization routine. An impossible state has been requested; no reason to keep going. @mszulcz-mitre are there any drawbacks that you can think of from preferring the check in `::init()`?

**Comment by mszulcz-mitre** [comment]
@HalosGhost I can't think of any significant drawbacks to adding the code to `::init()`.  As you pointed out, an impossible state has been requested, so I think it makes sense for initialization to fail.
