### ISSUE TITLE
Running environment lacks shared libraries

### ISSUE THREAD

**Issue by xczh** [mit-dci/opencbdc-tx#195]
### Affected Branch

trunk

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [X] The issue is reproducible in docker

### Description

In order to reproduce the issue, follow these steps:

1. Just follow the README documentation, run this command: `docker compose --file docker-compose-2pc.yml up --build` or `docker compose --file docker-compose-atomizer.yml up --build`.
2. Image compilation completed successfully.
3. However, the following errors will occur during the runtime: 

For twophase:

```
opencbdc-tx-shard0-1        | ./build/src/uhs/twophase/locking_shard/locking-shardd: error while loading shared libraries: libsnappy.so.1: cannot open shared object file: No such file or directory
opencbdc-tx-shard0-1 exited with code 127
opencbdc-tx-coordinator0-1  | ./build/src/uhs/twophase/coordinator/coordinatord: error while loading shared libraries: libsnappy.so.1: cannot open shared object file: No such file or directory
opencbdc-tx-coordinator0-1 exited with code 127
```

 For atomizer:

```
opencbdc-tx-atomizer0-1    | ./build/src/uhs/atomizer/atomizer/atomizer-raftd: error while loading shared libraries: libsnappy.so.1: cannot open shared object file: No such file or directory
opencbdc-tx-atomizer0-1 exited with code 127
opencbdc-tx-archiver0-1    | ./build/src/uhs/atomizer/archiver/archiverd: error while loading shared libraries: libsnappy.so.1: cannot open shared object file: No such file or directory
opencbdc-tx-shard0-1       | ./build/src/uhs/atomizer/shard/shardd: error while loading shared libraries: libsnappy.so.1: cannot open shared object file: No such file or directory
canceled
opencbdc-tx-archiver0-1 exited with code 0
```

It seems that it is caused by the lack of snappy compression library at runtime. I will try to fix this problem. A PR will be submitted later for processing :grinning:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HalosGhost** [comment]
Thanks for looking into this! Have you taken a look at #193? I'd actually imagine this issue is solved by it (we're working to fix a CI bug, after which #193 will be merged).

**Comment by xczh** [comment]
Sorry I didn't notice #193. It seems that you are trying to remove the dependency of `snappy`. However, the lack of `snappy` dependency in the current trunk branch code will cause compilation failure. I think the default branch should always be compiled and run successfully. The user should be able to complete the test according to the instructions in the README document.

**Comment by HalosGhost** [comment]
@xczh I completely agree. The bottleneck on the CI issue is far less than ideal, but we are actively working on it. There's nothing to stop us from merging #193 before the CI issue is fixed, but doing so sets a precedent I don't love.

**Comment by xczh** [comment]
I see. After the #193 is merged, if everything is OK, I think this issue can be closed too. Thank you for your kindly reply :wink:
