### ISSUE TITLE
have question about file

### ISSUE THREAD

**Issue by youngseoka** [mit-dci/opencbdc-tx#245]
[docker-compose-atomizer.yml](https://github.com/mit-dci/opencbdc-tx/blob/trunk/docker-compose-atomizer.yml)

in this file

 watchtower0:
    build:
      context: .
      target: atomizer
    image: opencbdc-tx-atomizer
    tty: true
    command: ./build/src/uhs/atomizer/watchtower/watchtowerd atomizer-compose.cfg 0
    ports:
      - 8555:8555
    expose:
      - "8556"

why port is 8555:8555 but expose 8556?

is this right?

**Comment by HalosGhost** [comment]
[`ports`](https://docs.docker.com/compose/compose-file/compose-file-v3/#ports) and [`expose`](https://docs.docker.com/compose/compose-file/compose-file-v3/#expose) are separate sections in docker-compose, and though they work similarly (both make ports available to other services outside the container but connected to the same network), but `expose` doesn't publish the port to the host (they are only available to linked services). In short, this configuration binds `8555` to the host's `8555` and exposes `8556` to linked services (but not to the host).

Does that make more sense?

**Comment by HalosGhost** [comment]
I'm going to close this for now; if you find you have more questions or need additional clarification, please feel free to comment and we can reopen if that makes sense!
