### ISSUE TITLE
Error with the docker build:  Unable to locally verify the issuer's authority

### ISSUE THREAD

**Issue by UrsaEli** [mit-dci/opencbdc-tx#31]
### Abstract

Error with the docker build:  Unable to locally verify the issuer's authority. 

### Description

Error with the docker build.

bash-3.2# docker build . -t opencbdc-tx 

"""
--2022-02-03 22:41:59--  https://github.com/google/leveldb/archive/1.22.tar.gz
Resolving github.com (github.com)... [IP]
Connecting to github.com (github.com)|[IP]|:443... connected.
ERROR: cannot verify github.com's certificate, issued by '....':
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
"""

After adding --no-check-certificate in 2 lines of Dockerfile, I hit another error

"""
+ . manifest.sh
++ ASIO_RELEASE=asio-1-12-0
++ pwd
+ PROJECT_DIR=/NuRaft-1.2.0
+ cd /NuRaft-1.2.0
+ '[' '!' -d asio ']'
+ git clone https://github.com/chriskohlhoff/asio.git ./asio
Cloning into './asio'...
fatal: unable to access 'https://github.com/chriskohlhoff/asio.git/': server certificate verification failed. CAfile: none CRLfile: none
"""

I also tried 

"""
RUN apt-get install ca-certificates # added to Dockerfile
"""
which gives
"""
E: Package 'ca-certificates' has no installation candidate
"""

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HalosGhost** [comment]
Hello! This looks a little like a local firewall (or similar network restriction) causing the connection to GitHub to fail. Can you try running on an unrestricted network?

**Comment by HalosGhost** [comment]
I'm going to go ahead and close this issue; please feel free to reopen this if you can provide some more information or show that it's not a network-restriction issue.
