### ISSUE TITLE
Improve the build system's ability to react to the target platform

### ISSUE THREAD

**Issue by HalosGhost** [mit-dci/opencbdc-tx#42]
We've seen several instances of people trying to build the code on slightly (or wildly) different platforms from the one we “officially” support (namely, x64 Linux), and it resulting in similar build errors (cf. #35)

In particular, our build system currently hard-codes some flags that we want to set for performance, but aren't available on all platforms. It would be ideal if we could teach our CMake files to dynamically define performance-related flags based on the target architecture to fix these problems more systemically (than offering specific suggestions to people to fix the build for their target). This should also just generally make the code more portable!

**Comment by centralbankdigitalcurrency** [comment]
👌👍
