### ISSUE TITLE
Technical Reference Link 404s 

### ISSUE THREAD

**Issue by temucin** [mit-dci/opencbdc-tx#51]
### Affected Branch

The hyperlink for the Technical Reference in _getting-started.md_ goes to a 404 site.  Not sure if its an issue with the host site or if the link is incorrect. 

`* The [Technical Reference](https://mit-dci.github.io/opencbdc-tx/) includes documentation for the code itself and how it works`

![image](https://user-images.githubusercontent.com/7648487/153696679-679680b6-6106-4318-8064-0c68673b31d7.png)

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [X] The issue is reproducible in docker

### Description

In order to reproduce the issue, follow these steps:

1. Click hyperlink text "Technical Reference" in _getting-started.md_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HalosGhost** [comment]
Indeed! The doxygen documentation can be built locally, and is built as a part of our CI. We're working on getting it auto-deploying from new merges into gh-pages!

**Comment by HalosGhost** [comment]
I've manually published the latest version of the documentation on gh-pages, and it will be replaced with an automated deployment as soon as possible!
