### ISSUE TITLE
restart  locking_shard failed because unable to find dtx data 

### ISSUE THREAD

**Issue by tanqiwen** [mit-dci/opencbdc-tx#56]
### Affected Branch

trunk

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [ ] The issue is reproducible in docker

### Description

In order to reproduce the issue, follow these steps:

1.  I build opencbdc project and excute on ubuntu lts 20.04 on real machine (not in docker)
2. start the sentineld,coordinatord,locking-shardd on machine a for one sharding
3. then i modify config ,and start sentineld,coordinatord,locking-shardd on two machine（machine a ,machine b） for two sharding ,for machine a i have clear file shad0*.data shad*_log,coordinator*.data,coordinator*log,
4. but start locking_shard on machine a failed ,report error" [FATAL] Unable to find dtx data for apply XXXX)

how we can start locking_shard?Are there any other cache files that need to be cleaned?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by metalicjames** [comment]
It sounds like one of the coordinators is trying to recover a previously failed transaction, but the shard has a new state, and thus knows nothing about this transaction. All the files will be created in the working directory, so if you make sure that's clear, there shouldn't be any residual state between runs.
