### ISSUE TITLE
updating a source file does not propagate to opt/tx-processor

### ISSUE THREAD

**Issue by llsuperpositionll** [mit-dci/opencbdc-tx#71]
### Affected Branch

mit-dci/opencbdc-tx

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [X] The issue is reproducible in docker

### Description

In order to reproduce the issue, follow these steps:

1. Modify a source file :  <homedir>/opencbdc-tx/src/uhs/client/**client-cli.cpp**
2. Issue command : docker build . -t opencbdc-tx (make sure that it compiles fine)
3. Issue command: docker-compose --file docker-compose-atomizer.yml up
![atom](https://user-images.githubusercontent.com/26781058/155804464-b1edb99c-d1da-423d-8495-ea5d5cd799b6.JPG)

4. Issued command : docker run --network atomizer-network -ti opencdbc-tx /bin/bash
   This will switch dir to: /opt/tx-processor
5. Check the source file located in this dir: **/opt/tx-processor**/src/uhs/client/client-cli.cpp 
This source file is still the original **unmodified** file, and does not contain the changes in step (1). This may be the reason the client-cli binary is unaffected by the changes made in (1).

Probably a docker syntax I may be getting wrong. But wanted to check it out here..

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dmtrinh** [comment]
It's likely one of the container layers in Step 2 did not get fully rebuilt.  Try running `docker build --no-cache`.

**Comment by llsuperpositionll** [comment]
Thanks. Definitely something to do with caching. 

I tried the _--no-cache_ option, but still had same issue. Don't know if it's related to running WSL on Windows 10. 

Anyways, after deleting the 2 instances of _opencbdc-tx image_  in docker, and rebuilding (without _no-cache_), I was able to get past the issue, and try out a minor change:
![code](https://user-images.githubusercontent.com/26781058/155857347-34525a18-9794-4042-82ea-97b5a0ec930d.JPG)
![sync](https://user-images.githubusercontent.com/26781058/155857354-95faa4b9-ce87-4691-a6c9-bb9bda6efb58.JPG)

Just ran into something else, and probably it's a known issue:

In the **opencbdc-tx** docker container, if I click the **open in browser** option for either _opencbdc-tx-watchtower0-1_ or _opencbdc-tx-sentinel0-1_ processes, I see the process stops and _bad_alloc_ error message log in the console...

![bad_alloc](https://user-images.githubusercontent.com/26781058/155857333-ad1163a1-b6bc-4bb8-b049-058e8b2c4b04.JPG)

**Comment by dmtrinh** [comment]
Had a chance to test this briefly.  I could not reproduce the problem locally on my macOS 12.2 so it could be something strange going on with WSL.

Here's what I tried:

1.   Grab a fresh copy of the repo:
```git clone --recurse-submodules https://github.com/mit-dci/opencbdc-tx```
2.  Build
```docker build . -t opencbdc-tx```
3.  Make an innocuous change - e.g. capitalizing the text "Unknown" in `client-cli.cpp`
* e.g. ```sed -i "" 's/Unknown/UNKNOWN/' src/uhs/client/client-cli.cpp```
4.  Rebuild
```docker build . -t opencbdc-tx```
5.  After launching the system with docker compose and running some tests, I see the changes reflected both at runtime and when viewing the `client-cli.cpp` source file.

**Comment by llsuperpositionll** [comment]
> 
Thank you for checking. 

Just to confirm, did you run the steps (3-4-5) again a second time ? I guess the cached the copy would be the first one..

Yes, otherwise it's probably something strange with my WSL setup..

**Comment by HalosGhost** [comment]
I just had a chance to give a shot to this locally and I also cannot reproduce. When I modify files and go to rebuild the images, the output shows it rebuilding the code (and the cmake output shows that the specific files are rebuilt). On running the system, I see the modifications right away.

I'm going to mark this as `needs-more-information` for now; if anyone with a WSL setup available can dig-in and find a potential workaround/solution we can merge, that would be welcomed!
