### ISSUE TITLE
some question about process

### ISSUE THREAD

**Issue by CanYouGiveMeAName** [mit-dci/opencbdc-tx#91]
### Abstract

I had some doubts when I read the paper recently. But there is no contact information in the paper, so ask a question here, hope to get the answer, thank you!

1. efficacy of shard
2. doubt of `preventing double spends`

### Description

1. When all input UHS are in one shard, will this transaction send to atomizer? If so, how can user get result form watchtower; if not, atomizer should handler all transactions, how shard improve performance.

2. Only after shard get result of one transaction form atomizer, it can process another transaction? If so, it will be so inefficient. If not, send transaction with one UHS two consecutive times. When shard get these two, inputs are validate both.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HalosGhost** [comment]
@CanYouGiveMeAName just to double-check, are you still looking for answers to these questions? (It seems you closed the issue shortly after creating it.)

**Comment by CanYouGiveMeAName** [comment]
> @CanYouGiveMeAName just to double-check, are you still looking for answers to these questions? (It seems you closed the issue shortly after creating it.)

Thank you very much! I read the paper several times and found that I did not understand the transaction process before, which is why I had this question. But I still don't have a deep understanding of the role of fragmentation. Each shard processes every transaction, and the shard's role is just to share the pressure of writing data? As reading data in a set is very fast.

**Comment by narula** [comment]
> Thank you very much! I read the paper several times and found that I did not understand the transaction process before, which is why I had this question. But I still don't have a deep understanding of the role of fragmentation. Each shard processes every transaction, and the shard's role is just to share the pressure of writing data? As reading data in a set is very fast.

Hi @CanYouGiveMeAName -- each shard does _not_ process every transaction, in either architecture. 

> 1. When all input UHS are in one shard, will this transaction send to atomizer? If so, how can user get result form watchtower; if not, atomizer should handler all transactions, how shard improve performance.

Yes -- every eventually confirmed transaction is sent to the atomizer to be ordered into a block. Additional shards improve performance by removing the workload of checking input existence (memory, CPU, disk) from the lead atomizer, and enabling UHS sizes that are too large for one machine. We do see performance improvements as we increase the number of shards.

But I think it would be very useful to benchmark a combined atomizer+shard, especially if we're discussing UHS sizes in the billions -- that should fit on one machine.

> 2. Only after shard get result of one transaction form atomizer, it can process another transaction? If so, it will be so inefficient. If not, send transaction with one UHS two consecutive times. When shard get these two, inputs are validate both.

Shards can process transactions without knowing in a former transaction was confirmed -- it attaches a block height to every attestation, which might be stale. The atomizer manages attestations that might come from stale block heights using the STXO cache. This is described in section 4.2 of the paper.
