### ISSUE TITLE
Some local tests may fail if port number is not available

### ISSUE THREAD

**Issue by davebryson** [mit-dci/opencbdc-tx#97]
### Affected Branch

trunk

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [ ] The issue is reproducible in docker

### Description

Testing outside of Docker may fail if a port number is needed for the test and the port is in use.  In some cases, this may result in a seg fault  which can be misleading.  For example, the unit tests in `raft_test.app` create 3 nodes using the port range 5000-5002.  The port range has caused seg faults on my machine as port 5000 was in use.  Changing the ports resolves the issue.

I'm not sure what the best fix for this is.  Finding available ports (in code) can be a little tricky and unreliable.  The other alternative is to just test in Docker and specify that testing outside of Docker is not recommended....

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HalosGhost** [comment]
I've run into this before, and we do have one potential solution for it housed under #3 (particularly in the task `Add support for OS-assigned ephemeral port numbers and leverage them in-tests`).

It should be possible to listen on port 0 (which should fetch an available port).

**Comment by HalosGhost** [comment]
via #289.
